import { ChargeableItemPrice } from '../chargeableItemPrice';
import { ExamRegStatusEnum } from '../enums/examRegStatus';
import { MedProductTypeEnum } from '../enums/medProductType';
import { RecordStateEnum } from '../enums/recordState';
import { Staff } from '../staff';

export interface MedRegItemBase {
  specialNote?: string | null;
  examRegStatus?: ExamRegStatusEnum;
  isCountHI?: boolean;
  isCountPatient?: boolean;
  isCountHI_Orig?: boolean;
  isCountPatient_Orig?: boolean;
  isPackageService?: boolean;
  isInPackage?: boolean;
  v_NewPriceType?: number;
  reasonChangePrice?: string | null;
  isModItemOK?: boolean;
  doctorStaff?: Staff | null;
  doctorStaff_Orig?: Staff | null;
  medicalInstructionDate?: string | null;
  medicalInstructionDate_Orig?: string | null;
  resultDate?: string | null;
  discountAmt?: number;
  isDiscounted?: boolean;
  totalDiscountAmount?: number;
  promoDiscProgID?: number | null;
  isDiscountChecked?: boolean;
  intPtDiagDrInstructionID?: number | null;
  countValue?: number;
  tickTime?: number | null;
  displayID?: number;
  selectedItem?: boolean;
  v_CpoeImplementationProgress?: number | null;
  cpoeImplementationProgressNotes?: string | null;
  cancelStaffName?: string | null;
  paidStaffName?: string | null;
  paidStaffID?: number;
  refundTime?: string | null;
  iD?: number;
  hiApplied?: boolean;
  invoicePrice?: number;
  hiAllowedPrice?: number | null;
  priceDifference?: number;
  hiPayment?: number;
  patientCoPayment?: number;
  patientPayment?: number;
  qty?: number;
  totalInvoicePrice?: number;
  totalPriceDifference?: number;
  totalHIPayment?: number;
  hiPaymentLimit?: number;
  totalCoPayment?: number;
  chargeableItem?: ChargeableItemPrice | null;
  paidTimeTmp?: string | null;
  paidTime?: string | null;
  hiBenefit?: number | null;
  staffID?: number | null;
  chargeableItemName?: string | null;
  totalPatientPayment?: number;
  chargeableItemCode?: string | null;
  createdDate?: string;
  recordState?: RecordStateEnum;
  hisID?: number | null;
  paymentRateOfHIAddedItem?: number | null;
  maxQtyHIAllowItem?: number | null;
  maskedHIAllowedPrice?: number | null;
  medProductType?: MedProductTypeEnum;
  totalHIPaymentLimit?: number;
}
