import { PrescriptionDetail } from './prescriptionDetail';
import { Staff } from '../staff';
import { DiagnosisTreatment } from './diagnosisTreatment';
import { PrescriptionIssueHistory } from './prescriptionIssueHistory';
import { RefDepartment } from '../reference/refDepartment';
import { RegistrationTypeEnum } from '../enums/registrationType';

export type Prescription = {
  prescriptID?: number;
  issue_HisID?: number;
  consultantID?: number;
  diagnosis?: string;
  objDiagnosisTreatment?: DiagnosisTreatment;
  doctorAdvice?: string;
  forOutPatient?: boolean;
  haveBeenConsulted?: boolean;
  v_PrescriptionType?: number;
  v_PrescriptionIssuedCase?: number;
  prescriptionDetails?: PrescriptionDetail[];
  prescriptionIssueHistory?: PrescriptionIssueHistory;
  consultantDoctor?: Staff;
  secretaryStaff?: Staff; 
  creatorStaffID?: number;
  objCreatorStaffID?: Staff;
  modifierStaffID?: number;
  recDateCreated?: string;
  selNDay?: number;
  selApptDate?: string;
  nDay?: number;
  hasAppointment?: boolean;
  preNoDrug?: boolean;
  iCD10List?: string;
  refGenDrugCatID_1?: number;
  categoryName?: string;
  department?: RefDepartment;
  isEmptyPrescription?: boolean;
  prescriptionIssueCode?: string;
  isWarningSimilar?: boolean;
  isWarningInteraction?: boolean;
  medNameUseOnlyForCheckConsultation?: string;
  medSecretaryID?: number;
  reason?: string;
  isOutsideRegimen?: boolean;
  confirmedDTItemID?: number;
  percentExceed?: number;
  v_RegistrationStatus?: number;
  toaThuocVuotTran?: boolean;
  repeat?: number;
  isPrimaryPrescription?: boolean;
  isTimeSlotAppointment?: boolean;
  v_RegistrationType?: RegistrationTypeEnum;
  needToHoldConsultation?: boolean;
  hICardNo?: string;
  isSold?: boolean;
  prescriptDetailsStr?: string;
  issueID?: number;
  serviceRecID?: number;
  appointmentID?: number;
  appointmentDate?: string;
  issuedDateTime?: string;
  origIssuedDateTime?: string;
  objIssuerStaffID?: Staff;
  timesNumberIsPrinted?: number;
  originalPrescriptID?: number;
  v_PrescriptionNotes?: number;
  allergiesString?: string;
  warningString?: string;
  patientID?: number;
  patientCode?: string;
  patientFullName?: string;
  ptRegistrationID?: number;
  ptRegistrationCode?: string;
  examDate?: string;
  v_ProcessingType?: number;
  processingType?: string;
  v_Behaving?: number;
  behaving?: string;
  patientRecID?: number;
  nationalMedicalCode?: string;
  patientRecBarCode?: string;
  isAllowEditNDay?: boolean;
  ptRegDetailID?: number;

}
