import { PatientClassification } from '../reference/patientClassification';
import { CitiesProvince, SuburbNames, WardNames } from '../reference/refCountry';
import { IGender } from './gender';
import { HealthInsuranceExt } from './healthInsuranceExt';

export interface Patient {
  patientID?: number;
  patientCode?: string;
  avatarUrl?: string; 
  fullName?: string;
  patientFullStreetAddress?: string;
  patientStreetAddress?: string;
  dateBecamePatient?: string;
  gender?: string;
  dob?: string;
  monthsOld?: number;
  age?: number;
  ageString?: string;
  patientOccupation?: string;
  patientCellPhoneNumber?: string;
  firstName?: string;
  middleName?: string;
  lastName?: string;
  ageOnly?: boolean;
  genderObj?: IGender;
  patientEmployer?: string;
  generalInfoString?: string;
  dobText?: string;
  yob?: number;
  patientPhoneNumber?: string;
  fileCodeNumber?: string;
  consultingDiagnosysID?: number;
  file?: string;
  citiesProvince?: CitiesProvince;
  suburbName?: SuburbNames;
  suburbNameID?: number;
  cityProvinceID?: number;
  fContactFullName?: string;
  v_FamilyRelationship?: number;
  fromAppointment?: boolean;
  bloodTypeID?: number;
  wardName?: WardNames;
  v_Ethnic?: number;
  fullPath?: string;
  wardNameID?: number;
  dobForBaby?: string;
  currentHealthInsurance?: HealthInsuranceExt;
  currentClassification?: PatientClassification;
  familyRelationShipStatus?: boolean;
}
