export {};

// export interface SaveAndUpdateDiagPreRequest {
//     isUpdateWithoutChangeDoctorIDAndDatetime?: boolean;
//     aDiagnosisTreatment?: DiagnosisTreatment;
//     diagnosisIcd10ListID?: number;
//     aDiagnosisIcd10Items?: DiagnosisIcd10Items[];
//     numberTypePrescriptions_Rule?: number;
//     aPrescription?: Prescription;
//     aPrescription_Old?: Prescription;
//     allowUpdateThoughReturnDrugNotEnough?: boolean;
//     isCreateNewForOutTreatment?: boolean;
//     updatedSmallProcedure?: SmallProcedure;
//     staffID?: number;
//     ptRegistrationID?: number;
//     objGenExam?: GeneralExamination;
//     objApptServiceDetail?: PatientApptServiceDetails;
// }

// export interface DiagnosisTreatment {
//     dTItemID?: number;
//     serviceRecID?: number ;
//     ptRegDetailID?: number;
//     diagnosis?: string;
//     diagnosisFinal?: string;
//     orientedTreatment?: string;
//     doctorComments?: string;
//     huongDieuTri?: string;
//     mDRptTemplateID?: number;
//     doctorStaffID?: number;
//     objDoctorStaffID?: Staff;
//     deptLocationID?: number;
//     latestPrescriptID?: number ;
//     prescriptID?: number ;
//     issueID?: number ;
//     treatment?: string;
//     modifierDoctorNames?: string;
//     diagnosisDate?: string;
//     v_DiagnosisType?: number;
//     lookupDiagnosis?: Lookup;
//     v_TreatmentType?: number;
//     phyExamID?: number ;
//     patientServiceRecord?: PatientServiceRecord;
//     v_RegistrationType?: RegistrationType;
//     iCD10List?: string;
//     department?: RefDepartment;
//     heartFailureType?: boolean;
//     treatmentType?: string;
//     markedDelete?: boolean;
//     iCD10Code?: string;
//     medSecretaryID?: number;
//     versionNumber?: number;
//     deptIDCreated?: number;
// }

// export interface DiagnosisIcd10Items {
//     diagIcd10ItemID?: number;
//     diagnosisIcd10ListID?: number;
//     iCD10Code?: string;
//     v_DiagIcdStatus?: number;
//     isMain?: boolean;
//     isCongenital?: boolean;
//     diseasesReference?: DiseasesReference;
//     lookupStatus?: Lookup;
//     isInvalid?: boolean;
//     recordState?: RecordState;
//     countValue?: number;
// }

// export interface Prescription {
//     prescriptID?: number;
//     issue_HisID?: number ;
//     consultantID?: number ;
//     diagnosis?: string;
//     objDiagnosisTreatment?: DiagnosisTreatment;
//     doctorAdvice?: string;
//     forOutPatient?: boolean ;
//     haveBeenConsulted?: boolean ;
//     v_PrescriptionType?: number ;
//     v_PrescriptionIssuedCase?: number ;
//     prescriptionDetails?: PrescriptionDetail[];
//     prescriptionIssueHistory?: PrescriptionIssueHistory;
//     creatorStaffID?: number;
//     objCreatorStaffID?: Staff;
//     modifierStaffID?: number ;
//     recDateCreated?: string;
//     selNDay?: number;
//     selApptDate?: string ;
//     nDay?: number ;
//     hasAppointment?: boolean;
//     preNoDrug?: boolean;
//     iCD10List?: string;
//     refGenDrugCatID_1?: number;
//     categoryName?: string;
//     department?: RefDepartment;
//     isEmptyPrescription?: boolean;
//     prescriptionIssueCode?: string;
//     isWarningSimilar?: boolean;
//     isWarningInteraction?: boolean;
//     medNameUseOnlyForCheckConsultation?: string;
//     medSecretaryID?: number;
//     reason?: string;
//     isOutsideRegimen?: boolean;
//     confirmedDTItemID?: number;
//     percentExceed?: number;
//     v_RegistrationStatus?: number;
//     toaThuocVuotTran?: boolean;
//     repeat?: number;
//     isPrimaryPrescription?: boolean;
//     isTimeSlotAppointment?: boolean;
//     v_RegistrationType?: RegistrationType;
//     needToHoldConsultation?: boolean;
//     hICardNo?: string;
//     isSold?: boolean;
//     prescriptDetailsStr?: string;
//     issueID?: number;
//     serviceRecID?: number ;
//     appointmentID?: number ;
//     appointmentDate?: string ;
//     issuedDateTime?: string ;
//     origIssuedDateTime?: string ;
//     objIssuerStaffID?: Staff;
//     timesNumberIsPrinted?: number ;
//     originalPrescriptID?: number ;
//     v_PrescriptionNotes?: number ;
//     allergiesString?: string;
//     warningString?: string;
//     patientID?: number ;
//     patientCode?: string;
//     patientFullName?: string;
//     ptRegistrationID?: number ;
//     ptRegistrationCode?: string;
//     examDate?: string ;
//     v_ProcessingType?: number ;
//     processingType?: string;
//     v_Behaving?: number ;
//     behaving?: string;
//     patientRecID?: number;
//     nationalMedicalCode?: string;
//     patientRecBarCode?: string;
//     isAllowEditNDay?: boolean;
// }
