import { MedRegItemBase } from '@core/models/appointments/medRegItemBase';
import { PCLResultParamImplementations } from '../appointments/pCLExamType';
import { ChargeableItemPrice } from '../chargeableItemPrice';
import { ExamRegStatusEnum } from '../enums/examRegStatus';
import { RecordStateEnum } from '../enums/recordState';
import { V_PCLRequestStatusEnum } from '../enums/vPCLRequestStatus';
import { V_PCLRequestTypeEnum } from '../enums/vPCLRequestType';
import { Patient } from '../patients/patient';
import { RefDepartment } from '../reference/refDepartment';
import { PatientPCLRequestDetail } from './patientPCLRequestDetail';
import { PatientServiceRecord } from './patientServiceRecord';

export interface PatientPCLRequest extends MedRegItemBase {
  patientPCLReqID?: number;
  ptRegDetailID?: number;
  serviceRecID?: number;
  reqFromDeptLocID?: number;
  reqFromDeptLocIDName?: string;
  pclDeptLocIDName?: string;
  diagnosis?: string;
  doctorComments?: string;
  isExternalExam?: boolean;
  isImported?: boolean;
  isCaseOfEmergency?: boolean;
  v_PCLMainCategory?: number;
  pclResultParamImpID?: number | null;
  objPCLResultParamImpID?: PCLResultParamImplementations;
  patientServiceRecord?: PatientServiceRecord;
  patientPCLRequestIndicators?: PatientPCLRequestDetail[];
  markedAsDeleted?: boolean;
  hiApplied?: boolean;
  iD?: number;
  invoicePrice?: number;
  hiAllowedPrice?: number | null;
  maskedHIAllowedPrice?: number | null;
  priceDifference?: number;
  hIPayment?: number;
  patientCoPayment?: number;
  patientPayment?: number;
  qty?: number;
  chargeableItem?: ChargeableItemPrice;
  hiBenefit?: number;
  paidTime?: string;
  refundTime?: string;
  examRegStatus?: ExamRegStatusEnum;
  totalInvoicePrice?: number;
  totalPriceDifference?: number;
  totalHIPayment?: number;
  totalCoPayment?: number;
  totalPatientPayment?: number;
  hisID?: number;
  hasNonPriceDetail?: boolean;
  createdDate?: string;
  agencyID?: number;
  pclRequestNumID?: string;
  reqFromDeptID?: number;
  requestedDepartment?: RefDepartment;
  isAllowToPayAfter?: number;
  patient?: Patient;
  templateFileName?: string;
  defaultNumFilmsRecv?: number;
  allowToPayAfter?: boolean;
  isPaid?: boolean;
  patientClassID?: number;
  isTransferredToRIS?: boolean;
  isCancelTransferredToRIS?: boolean;
  hosClientID?: number;
  hosClientContractID?: number;
  contractNo?: string;
  contractName?: string;
  companyName?: string;
  pclResultDate?: string;
  pclNameStr?: string;
  isExistsTemplate?: boolean;
  paramEnum?: number | null;
  pclExamTypeID?: number | null;
  pclReqItemID?: number | null;
  pclExamTypeCode?: string;
  pclExamTypeName?: string;
  v_ExamRegStatusName?: string;
  requestedDoctorName?: string;
  examDate?: string;
  staffID?: number;
  doctorStaffID?: number;
  staffIDName?: string;
  v_PCLRequestStatusName?: string;
  ptRegistrationID?: number;
  v_RegistrationType?: number;
  v_RegistrationStatus?: number;
  v_PCLRequestType?: V_PCLRequestTypeEnum;
  v_PCLRequestStatus?: V_PCLRequestStatusEnum;
  hosName?: string;
  recordState?: RecordStateEnum;
  deptID?: number;
  deptLocID?: number;
  serviceSeqNum?: number;
  serviceSeqNumType?: number;
  fullName?: string;
  patientCode?: string;
  patientID?: number;
  dTItemID?: number;
  iCD10List?: string;
  v_ExamRegStatus?: number;
  doctorIDName?: string;
  recCreatedDate?: string;
  packPCLReqID?: number;
  requestCreatedFrom?: number;
  pclDeptLocID?: number | null;
  pclReqCancelStaffID?: number;
}
