import { DiagnosisIcd10Items } from '../consultation/diagnosisIcd10Items';
import { DiagnosisTreatment } from '../consultation/diagnosisTreatment';
import { Hospital } from '../reference/hospital';
import { PatientRegistration } from '../patients/patientRegistration';
import { RefDepartment } from '../reference/refDepartment';

export interface TransferForm {
  transferFormID?: number;
  transferNum?: string;
  savingNumber?: string;
  curPatientRegistration?: PatientRegistration;
  transferFromHos?: Hospital;
  transferToHos?: Hospital;
  hospitalTransferName?: string;
  transferDate?: string;
  fromDate?: string;
  toDate?: string;
  transferFromDept?: RefDepartment;
  clinicalSign?: string;
  pCLResult?: string;
  usedServicesAndItems?: string;
  diagnosisTreatment?: string;
  iCD10?: string;
  diagnosisTreatment_Final?: string;
  iCD10Final?: string;
  transferType?: string;
  v_TransferTypeID?: number;
  transferReason?: string;
  v_TransferReasonID?: number;
  ptRegistrationID?: number;
  treatmentPlan?: string;
  treatmentResult?: string;
  v_TreatmentResultID?: number;
  cMKT?: string;
  v_CMKTID?: number;
  transVehicle?: string;
  transferBy?: string;
  v_PatientStatusID?: number;
  patientStatus?: string;
  v_TransferFormType?: number;
  isExistsError?: boolean;
  isDiffDiagnosis?: boolean;
  isActive?: boolean;
  markAsDeleted?: boolean;
  note?: string;
  patientFindBy?: number;
  lastDiagnosisTreatment?: DiagnosisTreatment;
  iCD10Main?: DiagnosisIcd10Items;
  tuNgay?: string;
  denNgay?: string;
}
